# Generated by Django 4.1.7 on 2023-04-01 08:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomJapaneseVocabularyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSubjectQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('fill in blank', 'fill in blank question'), ('build sentence', 'build a sentence given word bank')], max_length=14)),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_course_level', models.PositiveIntegerField(null=True)),
                ('subject_type', models.CharField(choices=[('alphabet', 'alphabet'), ('vocabulary', 'vocabulary'), ('grammar', 'grammar')], max_length=10)),
                ('has_unique_subject_model', models.BooleanField(default=False)),
                ('note', models.TextField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='languages.course')),
                ('course_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='languages.courselevels')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='languages.language')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('srs_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.spacedrepetitionsystem')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='SubjectExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.TextField()),
                ('audio_file', models.CharField(max_length=150, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectExampleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_example_translation', to='languages.language')),
                ('subject_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='subjects.subjectexample')),
            ],
        ),
        migrations.CreateModel(
            name='JapaneseSubject',
            fields=[
                ('subject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subjects.subject')),
                ('jlpt_level', models.IntegerField(choices=[(5, 'JLPT N5'), (4, 'JLPT N4'), (3, 'JLPT N3'), (2, 'JLPT N2'), (1, 'JLPT N1')], null=True)),
                ('japanese_subject_type', models.CharField(choices=[('kana', 'kana'), ('radical', 'radical'), ('kanji', 'kanji'), ('vocabulary', 'vocabulary'), ('grammar', 'grammar')], max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('subjects.subject', models.Model),
        ),
        migrations.CreateModel(
            name='SubjectExampleTranslationExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('translation_being_explained', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='subjects.subjectexampletranslation')),
            ],
        ),
    ]
