# Generated by Django 4.1.7 on 2023-04-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='japanesevocabulary',
            name='audio_file',
        ),
        migrations.CreateModel(
            name='JapaneseVocabularyAudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('last_high_pitch', models.PositiveIntegerField(null=True)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='subjects.japanesevocabulary')),
            ],
        ),
    ]
