# Generated by Django 4.1.7 on 2023-04-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_japanesevocabulary_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapaneseCounterWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1)),
                ('usage', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='japanesevocabulary',
            name='is_a_counter_word',
        ),
        migrations.CreateModel(
            name='JapaneseCounterWordSpecialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('reading', models.CharField(max_length=10)),
                ('explanation', models.TextField(null=True)),
                ('counter_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_numbers', to='subjects.japanesecounterword')),
            ],
        ),
        migrations.CreateModel(
            name='JapaneseCounterWordObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singular', models.CharField(max_length=20)),
                ('plural', models.CharField(max_length=20)),
                ('counter_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_this_is_used_to_count', to='subjects.japanesecounterword')),
            ],
        ),
        migrations.CreateModel(
            name='JapaneseCounterWordHowToAskForHowMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.CharField(max_length=10, null=True)),
                ('reading', models.CharField(max_length=10)),
                ('counter_word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='how_to_ask_for_how_many', to='subjects.japanesecounterword')),
            ],
        ),
        migrations.AddField(
            model_name='japanesevocabulary',
            name='counter_word_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='subjects.japanesecounterword'),
        ),
    ]
