# Generated by Django 4.1.7 on 2023-04-15 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_japanesecounterword_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptableResponsesButNotWhatLookingFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('reason', models.TextField()),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptable_responses_but_not_what_looking_for', to='subjects.japanesevocabulary')),
            ],
        ),
    ]
