# Generated by Django 4.1.7 on 2023-04-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_alter_grammar_options_alter_grammar_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsDifferencesExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_from_perspective_of_first_subject', models.TextField()),
                ('difference_from_perspective_of_second_subject', models.TextField()),
                ('first_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_subject', to='subjects.subject')),
                ('second_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_subject', to='subjects.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='differences_explanations',
            field=models.ManyToManyField(through='subjects.SubjectsDifferencesExplanation', to='subjects.subject'),
        ),
    ]
