# Generated by Django 4.1.7 on 2023-05-23 01:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_subjectsdifferencesexplanation_general_difference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiStrokeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke_paths', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='KanjiStrokeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('transform', models.CharField(max_length=30)),
                ('kanji_stroke_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_stroke_numbers', to='subjects.kanjistrokedata')),
            ],
        ),
        migrations.AddField(
            model_name='kanji',
            name='stroke_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanji', to='subjects.kanjistrokedata'),
        ),
    ]
