# Generated by Django 4.1.7 on 2023-05-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_characterstrokenumber_alter_kanji_stroke_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kana',
            name='stroke_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.characterstrokedata'),
        ),
    ]
