# Generated by Django 4.1.7 on 2023-04-01 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpacedRepetitionSystem',
            fields=[
                ('finished_position', models.PositiveIntegerField(choices=[(5, 5), (9, 9)])),
                ('name', models.CharField(choices=[('fast', 'system for easy subjects'), ('default', 'system for all other subjects')], max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpacedRepetitionSystemStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField(choices=[(1, '1st level'), (2, '2nd level'), (3, '3rd level'), (4, '4th level'), (5, 'Final level for quick subjects'), (6, '6th level'), (7, '7th level'), (8, '8th level'), (9, 'Final level for normal subjects')])),
                ('time_until_next_review', models.PositiveIntegerField(choices=[(2, '2 hours'), (4, '4 hours'), (8, '8 hours'), (24, '1 day'), (48, '2 days'), (168, '1 week'), (336, '2 weeks'), (720, '1 month'), (2880, '4 months')], null=True)),
                ('system_this_belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='reviews.spacedrepetitionsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review_date', models.DateTimeField(null=True)),
                ('user_already_knows_this', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('already_answered_reading_correctly', models.BooleanField(default=False)),
                ('already_answered_meaning_correctly', models.BooleanField(default=False)),
                ('times_got_reading_incorrect', models.PositiveIntegerField(default=0)),
                ('times_got_meaning_incorrect', models.PositiveIntegerField(default=0)),
                ('times_user_attempted_reading', models.PositiveIntegerField(default=0)),
                ('times_user_attempted_meaning', models.PositiveIntegerField(default=0)),
                ('times_this_was_completed', models.PositiveBigIntegerField(default=0)),
                ('current_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.spacedrepetitionsystemstages')),
            ],
            options={
                'ordering': ('next_review_date',),
            },
        ),
    ]
