# Generated by Django 4.1.7 on 2023-05-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_stripe_customer_id_user_stripe_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_subscription_id',
        ),
    ]
