# Generated by Django 4.1.7 on 2023-05-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscription_user_and_more'),
        ('users', '0003_remove_user_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='subscriptions.subscription'),
        ),
    ]
