# Generated by Django 4.1.7 on 2023-05-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_to_update_payment_information',
            field=models.BooleanField(default=False),
        ),
    ]
