# Generated by Django 4.1.7 on 2023-05-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_needs_to_update_payment_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='planType',
        ),
    ]
