# Generated by Django 4.1.7 on 2023-05-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_emails_review_threshold',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='wants_reminder_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_of_subjects_to_teach_per_lesson',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='srs_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='srs_subjects_added_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
