# Generated by Django 4.1.7 on 2023-05-27 22:55

from django.db import migrations
import uuid

def gen_uuid(apps, _):
    user_model = apps.get_model('users', 'User')
    all_connected_models = [
        apps.get_model('articles', 'UsersArticleProgress'),
        apps.get_model('languages', 'UsersProgressOnTest'),
        apps.get_model('languages', 'UserEnrolledInLanguage'),
        apps.get_model('languages', 'UsersProgressOnCourse'),
        apps.get_model('reviews', 'Review'),
        apps.get_model('stories', 'UsersProgressOnStory'),
        apps.get_model('streaks', 'DatesStudied'),
    ]

    for user_row in user_model.objects.all():
        user_row.uuid = uuid.uuid4()
        user_row.save(update_fields=['uuid'])
        for model in all_connected_models:
            for model_instance in model.objects.all():
                model_instance.user_uuid = user_row.uuid
                model_instance.save(update_fields=['user_uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_uuid'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]