# Generated by Django 4.1.7 on 2023-05-27 22:55

from django.db import migrations, models
import uuid

def transfer_foreign_key_values(apps, _):
    all_connected_models = [
        ('articles', 'UsersArticleProgress'),
        ('languages', 'UsersProgressOnTest'),
        ('languages', 'UserEnrolledInLanguage'),
        ('languages', 'UsersProgressOnCourse'),
        ('reviews', 'Review'),
        ('stories', 'UsersProgressOnStory'),
        ('streaks', 'DatesStudied'),
    ]

    for [module, model_name] in all_connected_models:
        migrations.RemoveField(model_name, 'user')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_populate_uuid_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RunPython(transfer_foreign_key_values, reverse_code=migrations.RunPython.noop),
    ]
