# Generated by Django 4.1.7 on 2023-05-28 05:39

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_uuid_null'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='id',
        )
    ]
