# Generated by Django 4.1.7 on 2023-05-20 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users_that_have_read_this',
            field=models.ManyToManyField(related_name='read_articles', through='articles.UsersArticleProgress', to=settings.AUTH_USER_MODEL),
        ),
    ]
