# Generated by Django 4.1.7 on 2023-05-20 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_users_that_have_read_this'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('additional_reading', 'Suggested article for the user to read after they finish their current one'), ('prerequisite', "Suggested article for users to read before reading the current article if they aren't familiar with what is taught in the prereq article")], max_length=19)),
                ('explanation', models.CharField(max_length=200)),
                ('article_being_linked_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_that_links_to_this_info', to='articles.article')),
                ('article_with_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_this_links_to_info', to='articles.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='linked_articles',
            field=models.ManyToManyField(related_name='articles_that_link_to_this', through='articles.LinkedArticles', to='articles.article'),
        ),
    ]
