# Generated by Django 4.1.7 on 2023-05-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_linkedarticles_article_linked_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='name',
            field=models.CharField(choices=[('vocabulary', 'vocabulary'), ('grammar', 'grammar'), ('speaking', 'speaking'), ('listening', 'listening'), ('kanji', 'kanji'), ('alphabet', 'alphabet'), ('kana', 'kana'), ('learning', 'general language learning')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='linkedarticles',
            name='relationship',
            field=models.CharField(choices=[('additional_reading', 'Suggested article for the user to read after they finish their current one'), ('prerequisite', "Suggested article for users to read before reading the current article if they aren't familiar with what is taught in the prereq article")], max_length=18),
        ),
    ]
