# Generated by Django 4.1.7 on 2023-05-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articletag_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersarticleprogress',
            name='user_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
