# Generated by Django 4.1.7 on 2023-05-28 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_usersarticleprogress_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersarticleprogress',
            name='user_uuid',
        ),
        migrations.AlterField(
            model_name='usersarticleprogress',
            name='user',
            field=models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='articles_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
