# Generated by Django 4.1.7 on 2023-04-01 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprogressonstory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_on_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storysectiontranslationexplanation',
            name='translation_being_explained',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='stories.storysectiontranslation'),
        ),
        migrations.AddField(
            model_name='storysectiontranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
        migrations.AddField(
            model_name='storysectiontranslation',
            name='story_section_being_translated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='stories.storysection'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='stories.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='languages.language'),
        ),
        migrations.AddField(
            model_name='story',
            name='users_stats',
            field=models.ManyToManyField(related_name='stories_stats', through='stories.UsersProgressOnStory', to=settings.AUTH_USER_MODEL),
        ),
    ]
