# Generated by Django 4.1.7 on 2023-05-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_audio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprogressonstory',
            name='user_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
