# Generated by Django 4.1.7 on 2023-04-01 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprogressoncourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_on_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersarticleprogress',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.article'),
        ),
        migrations.AddField(
            model_name='usersarticleprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userenrolledinlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
        migrations.AddField(
            model_name='userenrolledinlanguage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languagestandardslevels',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
        migrations.AddField(
            model_name='languagestandardslevels',
            name='level_it_starts_at',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standards_level', to='languages.courselevels'),
        ),
        migrations.AddField(
            model_name='language',
            name='users',
            field=models.ManyToManyField(related_name='languages', through='languages.UserEnrolledInLanguage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courselevels',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='languages.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='language_taught_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught_in_this_language', to='languages.language'),
        ),
        migrations.AddField(
            model_name='course',
            name='language_this_course_teaches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_teaching_this_language', to='languages.language'),
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='courses', through='languages.UsersProgressOnCourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlesection',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='languages.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='languages.language'),
        ),
        migrations.AddField(
            model_name='article',
            name='level_that_it_appears_before',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='languages.courselevels'),
        ),
        migrations.AddField(
            model_name='article',
            name='users_that_have_read_this',
            field=models.ManyToManyField(related_name='read_articles', through='languages.UsersArticleProgress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'language_this_course_teaches')},
        ),
    ]
