# Generated by Django 4.1.7 on 2023-05-01 13:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestForSkippingACoursesLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_encourage_user_to_take', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_points', to='languages.course')),
                ('levels_this_finishes_covering', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_that_ends_here', to='languages.courselevels')),
                ('levels_this_starts_to_cover', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_that_starts_here', to='languages.courselevels')),
            ],
        ),
        migrations.CreateModel(
            name='TestForSkippingACoursesLevelsCustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='languages.testforskippingacourseslevels')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
