# Generated by Django 4.1.7 on 2023-05-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0011_subjectsdifferencesexplanation_general_difference_and_more'),
        ('languages', '0003_testforskippingacourseslevels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestionForTestForSkippingACoursesLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=20)),
                ('subjects_covered', models.ManyToManyField(related_name='custom_questions_for_test_that_cover_this', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='UsersProgressOnTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WrongChoicesForCustomQuestionForTestForSkippingACoursesLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choices', to='languages.customquestionfortestforskippingacourseslevels')),
            ],
        ),
        migrations.AddField(
            model_name='testforskippingacourseslevels',
            name='users_that_have_taken_this',
            field=models.ManyToManyField(related_name='tests_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testforskippingacourseslevels',
            name='text_to_encourage_user_to_take',
            field=models.TextField(unique=True),
        ),
        migrations.DeleteModel(
            name='TestForSkippingACoursesLevelsCustomQuestion',
        ),
        migrations.AddField(
            model_name='usersprogressontest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='users_progress_on_this', to='languages.testforskippingacourseslevels'),
        ),
        migrations.AddField(
            model_name='usersprogressontest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_on_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customquestionfortestforskippingacourseslevels',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='languages.testforskippingacourseslevels'),
        ),
    ]
