# Generated by Django 4.1.7 on 2023-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_testforskippingacourseslevels_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testforskippingacourseslevels',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
