# Generated by Django 4.1.7 on 2023-05-07 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0006_alter_testforskippingacourseslevels_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testforskippingacourseslevels',
            name='users_that_have_taken_this',
        ),
        migrations.AddField(
            model_name='testforskippingacourseslevels',
            name='users_that_have_taken_this',
            field=models.ManyToManyField(related_name='tests_taken', through='languages.UsersProgressOnTest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='customquestionfortestforskippingacourseslevels',
            unique_together={('question', 'answer')},
        ),
    ]
