# Generated by Django 4.1.7 on 2023-05-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0008_remove_usersprogressontest_passed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprogressontest',
            name='status',
            field=models.CharField(choices=[('Japanese', 'Japanese'), ('English', 'English')], default='never taken', max_length=11),
        ),
    ]
