# Generated by Django 4.1.7 on 2023-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_alter_usersprogressontest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('vocabulary', 'vocabulary'), ('grammar', 'grammar'), ('speaking', 'speaking'), ('listening', 'listening'), ('kanji', 'kanji'), ('alphabet', 'alphabet'), ('kana', 'kana')], max_length=10, null=True),
        ),
    ]
