# Generated by Django 4.1.7 on 2023-05-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0010_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
