# Generated by Django 4.1.7 on 2023-05-20 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('languages', '0012_remove_articlesection_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselevels',
            name='suggested_article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_that_uses_this', to='articles.article'),
        ),
    ]
