# Generated by Django 4.1.7 on 2023-05-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0013_alter_courselevels_suggested_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrolledinlanguage',
            name='user_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usersprogressoncourse',
            name='user_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usersprogressontest',
            name='user_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
