# Generated by Django 4.1.7 on 2023-05-28 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0014_userenrolledinlanguage_user_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenrolledinlanguage',
            name='user_uuid',
        ),
        migrations.RemoveField(
            model_name='usersprogressoncourse',
            name='user_uuid',
        ),
        migrations.RemoveField(
            model_name='usersprogressontest',
            name='user_uuid',
        ),
        migrations.AlterField(
            model_name='userenrolledinlanguage',
            name='user',
            field=models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersprogressoncourse',
            name='user',
            field=models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='progress_on_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersprogressontest',
            name='user',
            field=models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='progress_on_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
