# Generated by Django 4.1.7 on 2023-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Annual', 'Annual'), ('Lifetime', 'Lifetime'), ('None', 'Currently Not Subscribed')], max_length=8),
        ),
    ]
