# Generated by Django 4.1.7 on 2023-05-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
        migrations.AddField(
            model_name='subscription',
            name='needs_to_update_payment_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Annual', 'Annual'), ('Lifetime', 'Lifetime')], max_length=8, null=True),
        ),
    ]
