# Generated by Django 4.1.7 on 2023-05-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='needs_to_update_payment_information',
        ),
    ]
